import { StyleSheet, Platform } from "react-native";
import { SW, SH } from "./constants";

const BG = "#0A0E1A";
const CARD = "#111827";
const BORD = "#1E2A3A";
const TEXT = "#E8EDF5";
const MUTE = "#6B7A8D";

export const s = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#000" },
  resultRoot: { flex: 1, backgroundColor: BG },

  permWrap: {
    flex: 1,
    backgroundColor: BG,
    alignItems: "center",
    justifyContent: "center",
    padding: 32,
  },
  permIcon: { fontSize: 64, marginBottom: 20 },
  permTitle: { color: TEXT, fontSize: 22, fontWeight: "700", marginBottom: 28 },
  permBtn: {
    backgroundColor: "#4A9EFF",
    paddingHorizontal: 36,
    paddingVertical: 14,
    borderRadius: 12,
  },
  permBtnTxt: { color: "#fff", fontWeight: "700", fontSize: 16 },

  frame: {
    position: "absolute",
    top: SH * 0.17,
    left: SW * 0.05,
    right: SW * 0.05,
    bottom: SH * 0.22,
    alignItems: "center",
    justifyContent: "flex-end",
  },
  frameHint: { color: "rgba(255,255,255,0.55)", fontSize: 12, marginBottom: 12 },
  cTL: {
    position: "absolute",
    top: 0,
    left: 0,
    width: 30,
    height: 30,
    borderTopWidth: 3,
    borderLeftWidth: 3,
    borderColor: "#4A9EFF",
    borderTopLeftRadius: 8,
  },
  cTR: {
    position: "absolute",
    top: 0,
    right: 0,
    width: 30,
    height: 30,
    borderTopWidth: 3,
    borderRightWidth: 3,
    borderColor: "#4A9EFF",
    borderTopRightRadius: 8,
  },
  cBL: {
    position: "absolute",
    bottom: 0,
    left: 0,
    width: 30,
    height: 30,
    borderBottomWidth: 3,
    borderLeftWidth: 3,
    borderColor: "#4A9EFF",
    borderBottomLeftRadius: 8,
  },
  cBR: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: 30,
    height: 30,
    borderBottomWidth: 3,
    borderRightWidth: 3,
    borderColor: "#4A9EFF",
    borderBottomRightRadius: 8,
  },
  topBar: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: Platform.OS === "android" ? 40 : 14,
  },
  appName: { color: "#fff", fontSize: 17, fontWeight: "800", letterSpacing: 4 },
  topBtns: { flexDirection: "row", gap: 10 },
  iconBtn: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "rgba(0,0,0,0.5)",
    alignItems: "center",
    justifyContent: "center",
  },
  iconBtnTxt: { fontSize: 18 },
  bottomBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 24,
    paddingBottom: Platform.OS === "android" ? 28 : 44,
    paddingTop: 16,
    backgroundColor: "rgba(0,0,0,0.6)",
  },
  sideActions: {
    flexDirection: "row",
    gap: 12,
    width: 100,
    justifyContent: "flex-start",
  },
  sideSpacer: { width: 100 },
  gallBtn: { alignItems: "center" },
  gallTxt: { color: "rgba(255,255,255,0.7)", fontSize: 10, marginTop: 3 },
  capBadge: {
    position: "absolute",
    top: -4,
    right: -4,
    minWidth: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "#FFD700",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
  },
  capBadgeTxt: { color: "#0A0E1A", fontSize: 12, fontWeight: "800" },
  journalBar: {
    position: "absolute",
    top: Platform.OS === "android" ? 90 : 100,
    left: 12,
    right: 12,
    backgroundColor: "rgba(0,0,0,0.65)",
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: "rgba(255,215,0,0.45)",
  },
  journalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  journalTitle: { color: "#FFD700", fontSize: 13, fontWeight: "700" },
  journalCancel: { color: "#FF6B35", fontSize: 12, fontWeight: "700" },
  journalThumbs: { gap: 8, paddingVertical: 4 },
  journalThumb: {
    width: 52,
    height: 52,
    borderRadius: 8,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.25)",
    position: "relative",
  },
  journalThumbImg: { width: "100%", height: "100%" },
  journalThumbIdx: {
    position: "absolute",
    bottom: 2,
    right: 4,
    color: "#fff",
    fontSize: 10,
    fontWeight: "800",
    textShadowColor: "rgba(0,0,0,0.9)",
    textShadowRadius: 2,
  },
  capBtn: {
    width: 78,
    height: 78,
    borderRadius: 39,
    borderWidth: 4,
    borderColor: "#fff",
    padding: 5,
  },
  capInner: { flex: 1, borderRadius: 34, backgroundColor: "#fff" },

  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderColor: BORD,
  },
  backBtn: { paddingHorizontal: 4 },
  backTxt: { color: "#4A9EFF", fontSize: 15, fontWeight: "600" },
  headerTitle: { color: TEXT, fontSize: 16, fontWeight: "700", letterSpacing: 1 },

  card: {
    margin: 16,
    padding: 36,
    backgroundColor: CARD,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: BORD,
    alignItems: "center",
  },
  loadTxt: { color: TEXT, fontSize: 16, fontWeight: "600", marginTop: 20 },
  loadSub: { color: MUTE, fontSize: 12, marginTop: 8, textAlign: "center" },
  retryBtn: {
    marginTop: 24,
    backgroundColor: "#4A9EFF",
    paddingHorizontal: 28,
    paddingVertical: 12,
    borderRadius: 12,
  },
  retryTxt: { color: "#fff", fontWeight: "700", fontSize: 15 },

  statsRow: { flexDirection: "row", paddingHorizontal: 14, paddingTop: 14, gap: 8 },
  stat: {
    flex: 1,
    backgroundColor: CARD,
    borderRadius: 14,
    borderWidth: 1,
    padding: 12,
    alignItems: "center",
  },
  statVal: { fontSize: 17, fontWeight: "800", marginTop: 3 },
  statLabel: { color: MUTE, fontSize: 10, marginTop: 2 },

  tabs: { paddingHorizontal: 14, gap: 8 },
  tab: {
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 12,
    backgroundColor: CARD,
    borderWidth: 1,
    borderColor: BORD,
    alignItems: "center",
    minWidth: 72,
  },
  tabIcon: { fontSize: 18, marginBottom: 3 },
  tabLabel: { color: MUTE, fontSize: 10, fontWeight: "700" },

  imgCard: {
    margin: 14,
    backgroundColor: CARD,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: BORD,
    overflow: "hidden",
  },
  imgCardTitle: { fontSize: 14, fontWeight: "700", padding: 14 },
  pipeImg: { width: "100%", height: SH * 0.35, backgroundColor: "#050810" },
  noImg: { height: 160, alignItems: "center", justifyContent: "center" },

  txtCard: {
    marginHorizontal: 14,
    backgroundColor: CARD,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: BORD,
    overflow: "hidden",
  },
  txtHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 14,
    borderBottomWidth: 1,
    borderColor: BORD,
  },
  txtTitle: { color: TEXT, fontSize: 14, fontWeight: "700" },
  txtBody: {
    color: TEXT,
    fontSize: 13,
    lineHeight: 22,
    fontFamily: Platform.OS === "ios" ? "Courier New" : "monospace",
  },
  txtBodyAmharic: {
    color: TEXT,
    fontSize: 15,
    lineHeight: 26,
  },
  langBadge: {
    color: MUTE,
    fontSize: 11,
    textAlign: "center",
    marginTop: 4,
  },
  pageTabs: { paddingHorizontal: 14, gap: 8 },
  pageTab: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: CARD,
    borderWidth: 1,
    borderColor: BORD,
  },
  pageTabActive: { borderColor: "#4A9EFF", backgroundColor: "#4A9EFF18" },
  pageTabTxt: { color: MUTE, fontSize: 12, fontWeight: "600" },
  pageTabTxtActive: { color: "#4A9EFF" },
  textToggleRow: {
    flexDirection: "row",
    marginHorizontal: 14,
    marginTop: 10,
    gap: 8,
  },
  textToggle: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: CARD,
    borderWidth: 1,
    borderColor: BORD,
    alignItems: "center",
  },
  textToggleActive: { borderColor: "#00D68F", backgroundColor: "#00D68F18" },
  textToggleTxt: { color: MUTE, fontSize: 12, fontWeight: "600" },
  textToggleTxtActive: { color: "#00D68F" },
  txtActions: { flexDirection: "row", gap: 16 },
  actionLink: { color: "#4A9EFF", fontWeight: "700" },

  flowCard: {
    margin: 14,
    backgroundColor: CARD,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: BORD,
    padding: 16,
  },
  flowTitle: { color: MUTE, fontSize: 10, fontWeight: "700", letterSpacing: 2, marginBottom: 12 },
  flowRow: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 6 },
  flowStep: {
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: "center",
  },
  flowLabel: { fontSize: 9, fontWeight: "700", marginTop: 2 },
  arrow: { color: MUTE, fontSize: 13 },
});
